# Generated by Django 4.2.7 on 2023-12-07 06:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lead", "0003_lead_team"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lead",
            options={"ordering": ("name",)},
        ),
    ]
